//
//  SearchMoviesInteractor.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa
import Alamofire

final class SearchMoviesInteractor {
}

// MARK: - Extensions -

extension SearchMoviesInteractor: SearchMoviesInteractorInterface {

    func search(input: String) -> Single<SearchResponse> {
        return Single.create { (observer) -> Disposable in

            let request = AF.request(
                "https://www.omdbapi.com/?apiKey=\(Constants.apiKey)&s=\(input)",
                method: .post,
                encoding: JSONEncoding.default
            )

            request
                .validate()
                .responseDecodable(of: SearchResponse.self) { response in
                    switch response.result {
                    case .success(let searchResult):
                        observer(.success(searchResult))
                    case .failure(let error):
                        observer(.error(error))
                    }
                }

            return Disposables.create {
                request.cancel()
            }
        }
    }

}
