//
//  SearchMoviesViewController.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa
import SkyFloatingLabelTextField

final class SearchMoviesViewController: UIViewController {

    // MARK: - IBOutlets

    @IBOutlet private weak var inputTextField: SkyFloatingLabelTextField!
    @IBOutlet private weak var tableView: UITableView!
    
    // MARK: - Public properties -

    var presenter: SearchMoviesPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        configure()
    }
	
}

// MARK: - Extensions -

extension SearchMoviesViewController: SearchMoviesViewInterface {
}

private extension SearchMoviesViewController {

    func configure() {
        let output = SearchMovies.ViewOutput(
            inputText: inputTextField.rx.text.asDriver()
        )

        let input = presenter.configure(with: output)
    }

}
