//
//  SearchMoviesInterfaces.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol SearchResultDelegate {
    func process(result: SearchResponse.Movie)
}

protocol SearchMoviesWireframeInterface: WireframeInterface {
    func dismiss()
}

protocol SearchMoviesViewInterface: ViewInterface {
    func showLoading()
    func hideLoading()
}

protocol SearchMoviesPresenterInterface: PresenterInterface {
    func configure(with output: SearchMovies.ViewOutput) -> SearchMovies.ViewInput
}

protocol SearchMoviesInteractorInterface: InteractorInterface {
    func search(input: String) -> Single<SearchResponse>
}

enum SearchMovies {

    struct ViewOutput {
        let inputText: Driver<String?>
    }

    struct ViewInput {
        let items: Driver<[TableCellItem]>
    }

}
