//
//  SearchMoviesWireframe.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class SearchMoviesWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard.searchMovies

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: SearchMoviesViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = SearchMoviesInteractor()
        let presenter = SearchMoviesPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SearchMoviesWireframe: SearchMoviesWireframeInterface {
}
