//
//  SearchMoviesPresenter.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class SearchMoviesPresenter {

    // MARK: - Private properties -

    private unowned let view: SearchMoviesViewInterface
    private let interactor: SearchMoviesInteractorInterface
    private let wireframe: SearchMoviesWireframeInterface

    private let delegate: SearchResultDelegate

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    init(view: SearchMoviesViewInterface, interactor: SearchMoviesInteractorInterface, wireframe: SearchMoviesWireframeInterface, delegate: SearchResultDelegate) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.delegate = delegate
    }
}

// MARK: - Extensions -

extension SearchMoviesPresenter: SearchMoviesPresenterInterface {

    func configure(with output: SearchMovies.ViewOutput) -> SearchMovies.ViewInput {
        let items = handle(inputText: output.inputText)
        return SearchMovies.ViewInput(
            items: items
        )
    }

}

private extension SearchMoviesPresenter {

    func handle(inputText: Driver<String?>) -> Driver<[TableCellItem]> {

        let toCells: (SearchResponse) -> [TableCellItem] = { [unowned self] in
            $0.search.map { [unowned self] movie in
                let didSelect: () -> Void = { [unowned self] in
                    self.delegate.process(result: movie)
                    self.wireframe.dismiss()
                }
                return SearchResultCellItem(movie: movie, didSelect: didSelect)
            }
        }

        return inputText.compactMap { $0 }
            .filter { $0.count > 0 }
            .distinctUntilChanged()
            .debounce(.milliseconds(500))
            .flatMap { [unowned interactor] in interactor.search(input: $0).asDriver(onErrorDriveWith: .empty()) }
            .map(toCells)
    }
}
