//
//  ClassifierDetailsInterfaces.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 30.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol ClassifierDetailsWireframeInterface: WireframeInterface {
    func open(url: URL)
}

protocol ClassifierDetailsViewInterface: ViewInterface {
}

protocol ClassifierDetailsPresenterInterface: PresenterInterface {
    var data: ClassifierInfo { get }
    func configure(with output: ClassifierDetails.ViewOutput) -> ClassifierDetails.ViewInput
}

protocol ClassifierDetailsInteractorInterface: InteractorInterface {
}

enum ClassifierDetails {

    struct ViewOutput {
        let openLinkAction: Signal<Void>
    }

    struct ViewInput {
    }
}
