//
//  ClassifierDetailsInteractor.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 30.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class ClassifierDetailsInteractor {
}

// MARK: - Extensions -

extension ClassifierDetailsInteractor: ClassifierDetailsInteractorInterface {
}
