//
//  ClassifierDetailsWireframe.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 30.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ClassifierDetailsWireframe: BaseWireframe {

    // MARK: - Private properties

    private let storyboard = UIStoryboard.classifierDetails

    // MARK: - Module setup

    init(data: ClassifierInfo) {
        let moduleViewController = storyboard.instantiateViewController(ofType: ClassifierDetailsViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = ClassifierDetailsInteractor()
        let presenter = ClassifierDetailsPresenter(view: moduleViewController, interactor: interactor, wireframe: self, ClassifierInfo: data)
        moduleViewController.presenter = presenter
    }

}

// MARK: - ClassifierDetailsWireframeInterface

extension ClassifierDetailsWireframe: ClassifierDetailsWireframeInterface {

    func open(url: URL) {
        UIApplication.shared.open(url)
    }
}
