//
//  ChooseClassifierWireframe.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 29.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ChooseClassifierWireframe: BaseWireframe {

    // MARK: - Private properties

    private let storyboard = UIStoryboard.chooseClassifier

    // MARK: - Module setup

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: ChooseClassifierViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = ChooseClassifierInteractor()
        let presenter = ChooseClassifierPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - ChooseClassifierWireframeInterface

extension ChooseClassifierWireframe: ChooseClassifierWireframeInterface {

    func openClassifierDetails(with data: ClassifierInfo) {
        let wireframe = ClassifierDetailsWireframe(data: data)
        navigationController?.pushWireframe(wireframe)
    }
}
