//
//  ChooseClassifierInterfaces.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 29.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol ChooseClassifierWireframeInterface: WireframeInterface {
    func openClassifierDetails(with data: ClassifierInfo)
}

protocol ChooseClassifierViewInterface: ViewInterface {
}

protocol ChooseClassifierPresenterInterface: PresenterInterface {
    func configure(with output: ChooseClassifier.ViewOutput) -> ChooseClassifier.ViewInput
}

protocol ChooseClassifierInteractorInterface: InteractorInterface {
    var allClassifiers: [ClassifierInfo] { get }
    var classifierDriver: Driver<ClassifierModelType> { get }
    var currentClassifier: ClassifierModelType { get set }
}

enum ChooseClassifier {

    struct ViewOutput {
    }

    struct ViewInput {
        let items: Driver<[TableCellItem]>
    }
}
