//
//  ChooseClassifierPresenter.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 29.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ChooseClassifierPresenter {

    // MARK: - Private properties -

    private unowned let view: ChooseClassifierViewInterface
    private let interactor: ChooseClassifierInteractorInterface
    private let wireframe: ChooseClassifierWireframeInterface

    // MARK: - Lifecycle -

    init(view: ChooseClassifierViewInterface, interactor: ChooseClassifierInteractorInterface, wireframe: ChooseClassifierWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - ChooseClassifierPresenterInterface

extension ChooseClassifierPresenter: ChooseClassifierPresenterInterface {

    func configure(with output: ChooseClassifier.ViewOutput) -> ChooseClassifier.ViewInput {
        return ChooseClassifier.ViewInput(items: .just(createItems()))
    }

}

private extension ChooseClassifierPresenter {

    func createItems() -> [TableCellItem] {
        return interactor.allClassifiers
            .map { [unowned wireframe] data in ClassifierDescriptionCellItem(
                title: data.name,
                didSelectDetails: { [unowned wireframe] in wireframe.openClassifierDetails(with: data)
                })
            }
    }
}
