//
//  ChooseClassifierViewController.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 29.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ChooseClassifierViewController: UIViewController {

    // MARK: - IBOutlets

    @IBOutlet private weak var tableView: UITableView! {
        didSet {
            self.tableView.registerNib(cellOfType: ClassifierDescriptionTableViewCell.self)
        }
    }

    // MARK: - Public properties

    var presenter: ChooseClassifierPresenterInterface!

    // MARK: - Private properties

    private lazy var dataSourceDelegate: TableDataSourceDelegate = {
        return TableDataSourceDelegate(tableView: self.tableView)
    }()

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        configure()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
    }
}

// MARK: - ChooseClassifierViewInterface

extension ChooseClassifierViewController: ChooseClassifierViewInterface {
}

// MARK: - Configuration

private extension ChooseClassifierViewController {

    func configure() {
        let output = ChooseClassifier.ViewOutput()

        let input = presenter.configure(with: output)
        handle(items: input.items)
    }
}

// MARK: - Binding setup

private extension ChooseClassifierViewController {

    func handle(items: Driver<[TableCellItem]>) {
        items.drive(dataSourceDelegate.rx.items)
            .disposed(by: disposeBag)
    }
}
