//
//  ChooseClassifierInteractor.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 29.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class ChooseClassifierInteractor {
}

// MARK: - ChooseClassifierInteractorInterface

extension ChooseClassifierInteractor: ChooseClassifierInteractorInterface {

    var allClassifiers: [ClassifierInfo] {
        return ClassifierManager.allClassifiers
    }

    var currentClassifier: ClassifierModelType {
        get { return UserStoreManager.classifier }
        set(newValue) { UserStoreManager.classifier = newValue }
    }

    var classifierDriver: Driver<ClassifierModelType> {
        return UserStoreManager.classifierDriver
    }
}
