//
//  CreateReviewPresenter.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class CreateReviewPresenter {

    // MARK: - Private properties -

    private unowned let view: CreateReviewViewInterface
    private let interactor: CreateReviewInteractorInterface
    private let wireframe: CreateReviewWireframeInterface

    private let movieRelay = BehaviorRelay<String>(value: "")

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    init(view: CreateReviewViewInterface, interactor: CreateReviewInteractorInterface, wireframe: CreateReviewWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension CreateReviewPresenter: CreateReviewPresenterInterface {

    func configure(with output: CreateReview.ViewOutput) -> CreateReview.ViewInput {
        handle(searchMovie: output.searchMovieAction)
        return CreateReview.ViewInput(
            title: movieRelay.asDriver()
        )
    }

}

extension CreateReviewPresenter: SearchResultDelegate {

    func process(result: SearchResponse.Movie) {
        movieRelay.accept(result.title)
    }
}

private extension CreateReviewPresenter {

    func handle(searchMovie: Signal<Void>) {
        searchMovie.emit(onNext: { [unowned wireframe, unowned self] in wireframe.searchMovies(delegate: self) })
            .disposed(by: disposeBag)
    }
}
