//
//  CreateReviewViewController.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class CreateReviewViewController: UIViewController {

    // MARK: - IBOutlets

    @IBOutlet private weak var titleLabel: UILabel!

    // MARK: - Public properties -

    var presenter: CreateReviewPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        configure()
        setupUI()
    }
	
}

// MARK: - Extensions -

extension CreateReviewViewController: CreateReviewViewInterface {
}

private extension CreateReviewViewController {

    func configure() {
        let output = CreateReview.ViewOutput()

        let input = presenter.configure(with: output)
    }

}

private extension CreateReviewViewController {

    func setupUI() {
        titleLabel.text = Strings.createReviewTitle
    }
}
