//
//  CreateReviewWireframe.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class CreateReviewWireframe: BaseWireframe {

    // MARK: - Private properties

    private let storyboard = UIStoryboard.createReview

    // MARK: - Module setup

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: CreateReviewViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = CreateReviewInteractor()
        let presenter = CreateReviewPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - CreateReviewWireframeInterface

extension CreateReviewWireframe: CreateReviewWireframeInterface {

    func dismiss() {
        viewController.dismiss(animated: true, completion: nil)
    }
}
