//
//  CreateReviewInterfaces.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

struct ReviewData {
    let movieTitle: String?
    let movieYear: String?
    let reviewTitle: String?
    let reviewText: String?
}

protocol CreateReviewWireframeInterface: WireframeInterface {
    func showCreatedReviewAlert(with title: String, okMessage: String) -> Single<Void>
    func dismiss()
    func searchMovies(delegate: SearchResultDelegate)
}

protocol CreateReviewViewInterface: ViewInterface {
    func startLoading()
    func stopLoading()
    func reset()
}

protocol CreateReviewPresenterInterface: PresenterInterface {
    func configure(with output: CreateReview.ViewOutput) -> CreateReview.ViewInput
}

protocol CreateReviewInteractorInterface: InteractorInterface {
    func save(reviewData: ReviewData) -> Driver<Bool>
}

enum CreateReview {

    struct ViewOutput {
        let searchMovieAction: Signal<Void>
        let saveReviewAction: Signal<Void>
        let data: Driver<(String?, String?, String?, String?)>
    }

    struct ViewInput {
        let movieData: Driver<(title: String, year: String)>
    }
}
