//
//  CreateReviewInteractor.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class CreateReviewInteractor {
}

// MARK: - CreateReviewInteractorInterface

extension CreateReviewInteractor: CreateReviewInteractorInterface {

    func save(reviewData: ReviewData) -> Driver<Bool> {

        guard
            let movieTitle = reviewData.movieTitle, movieTitle.count > 0,
            let title = reviewData.reviewTitle, title.count > 0,
            let text = reviewData.reviewText, text.count > 0
        else { return Driver.just(false) }

        let review = Review(context: PersistanceManager.context)
        review.movieTitle = movieTitle
        review.movieYear = reviewData.movieYear
        review.reviewTitle = title
        review.reviewText = text
        review.reviewDate = currentDate
        review.sentiment = classify(text: reviewData.reviewText)

        PersistanceManager.saveContext()

        return Driver.just(true)
    }
}

private extension CreateReviewInteractor {

    var currentDate: String {
        let formatter = DateFormatter()
        formatter.timeStyle = .none
        formatter.dateStyle = .medium
        formatter.timeZone = TimeZone.current
        return formatter.string(from: Date())
    }

    func classify(text: String?) -> String? {
        guard let text = text else { return nil }
        return ClassifierManager.shared.classify(text: text)
    }
}
