//
//  CreateReviewInterfaces.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol CreateReviewWireframeInterface: WireframeInterface {
    func dismiss()
    func searchMovies(delegate: SearchResultDelegate)
}

protocol CreateReviewViewInterface: ViewInterface {
}

protocol CreateReviewPresenterInterface: PresenterInterface {
    func configure(with output: CreateReview.ViewOutput) -> CreateReview.ViewInput
}

protocol CreateReviewInteractorInterface: InteractorInterface {
}

enum CreateReview {

    struct ViewOutput {
        let searchMovieAction: Signal<Void>
    }

    struct ViewInput {
        let title: Driver<String>
    }

}
