//
//  CreateReviewWireframe.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class CreateReviewWireframe: BaseWireframe {

    // MARK: - Private properties

    private let storyboard = UIStoryboard.createReview

    // MARK: - Module setup

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: CreateReviewViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = CreateReviewInteractor()
        let presenter = CreateReviewPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - CreateReviewWireframeInterface

extension CreateReviewWireframe: CreateReviewWireframeInterface {

    func showCreatedReviewAlert(with title: String, okMessage: String) -> Single<Void> {

        return Single.create { [unowned viewController] observer -> Disposable in

            let action =
                UIAlertAction(
                    title: okMessage,
                    style: .default,
                    handler: { _ in observer(.success(())) }
                )

            let alert = UIAlertController(title: title, message: nil, preferredStyle: .alert)
            alert.addAction(action)

            viewController.present(alert, animated: true, completion: nil)

            return Disposables.create { }
        }
    }

    func dismiss() {
        viewController.dismiss(animated: true, completion: nil)
    }

    func searchMovies(delegate: SearchResultDelegate) {
        navigationController?.presentWireframe(
            SearchMoviesWireframe(delegate: delegate)
        )
    }
}
