//
//  HomeViewController.swift
//  nlp
//
//  Created by Ivana Mršić on 18.11.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class HomeViewController: UITabBarController {

    // MARK: - Public properties -

    var presenter: HomePresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
}

private extension HomeViewController {
    
    typealias ChildViewControllers = [NLPViewController]

    func setupView() {
        let output = Home.ViewOutput()

        let input = presenter.configure(with: output)
        
        let tabItems: (ChildViewControllers) -> ChildViewControllers = { (controllers: ChildViewControllers) -> (ChildViewControllers) in
            controllers.forEach { $0.tabBarItem =  $0.tabBarProperty?.item }
            return controllers
        }
        
        input.tabBars
            .map(tabItems)
            .drive(onNext: { [unowned self] in self.viewControllers = $0 })
            .disposed(by: disposeBag)
    }

}
