//
//  ClassifierInterfaces.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 17.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol ClassifierWireframeInterface: WireframeInterface {
}

protocol ClassifierViewInterface: ViewInterface {
}

protocol ClassifierPresenterInterface: PresenterInterface {
    func configure(with output: Classifier.ViewOutput) -> Classifier.ViewInput
}

protocol ClassifierInteractorInterface: InteractorInterface {
}

enum Classifier {

    struct ViewOutput {
        let classifyAction: Signal<String?>
    }

    struct ViewInput {
        let result: Driver<String?>
    }

}
