//
//  ClassifierViewController.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 17.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ClassifierViewController: NLPViewController {
    
    // MARK: - IBOutlets
    
    @IBOutlet private weak var titleLabel: UILabel!
    @IBOutlet private weak var inputTextView: UITextView!
    @IBOutlet private weak var classifyButton: UIButton!
    @IBOutlet private weak var resultLabel: UILabel!
    @IBOutlet private weak var infoLabel: UILabel!
    
    // MARK: - Public properties -

    var presenter: ClassifierPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        setupUI()
    }

}

// MARK: - Extensions -

extension ClassifierViewController: ClassifierViewInterface {
}

private extension ClassifierViewController {

    func setupView() {
        
        let classifyAction = classifyButton.rx.tap.asSignal()
            .withLatestFrom(inputTextView.rx.text.asSignal(onErrorSignalWith: .empty())) { $1 }
        
        let output = Classifier.ViewOutput(
            classifyAction: classifyAction
        )

        let input = presenter.configure(with: output)
        
        input.result
            .drive(resultLabel.rx.text)
            .disposed(by: disposeBag)
    }

    func setupUI() {
        titleLabel.text = "Classify your review"
        infoLabel.text = "Use this feature to rate sentiment of your review."
        classifyButton.setTitle("Classify", for: .normal)
        resultLabel.text = "Result"
    }
}
