//
//  ClassifierInteractor.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 17.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class ClassifierInteractor {
}

// MARK: - Extensions -

extension ClassifierInteractor: ClassifierInteractorInterface {
}
