//
//  ProfileInterfaces.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol ProfileWireframeInterface: WireframeInterface {
}

protocol ProfileViewInterface: ViewInterface {
}

protocol ProfilePresenterInterface: PresenterInterface {
    func configure(with output: Profile.ViewOutput) -> Profile.ViewInput
}

protocol ProfileInteractorInterface: InteractorInterface {
}

enum Profile {

    struct ViewOutput {
    }

    struct ViewInput {
        let items: Driver<[TableCellItem]>
    }

}
