//
//  ProfileViewController.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ProfileViewController: NLPViewController {

    // MARK: - IBOutlets

    @IBOutlet private weak var profileImageView: UIImageView!

    @IBOutlet private weak var usernameTitleLabel: UILabel!
    @IBOutlet private weak var usernameLabel: UILabel!

    @IBOutlet private weak var emailTitleLabel: UILabel!
    @IBOutlet private weak var emailLabel: UILabel!

    @IBOutlet private weak var ratingsCountTitleLabel: UILabel!
    @IBOutlet private weak var ratingsCountLabel: UILabel!

    @IBOutlet private weak var ratingsSectionLabel: UILabel!
    @IBOutlet private weak var addRatingButton: UIButton!
    
    @IBOutlet private weak var tableView: UITableView! {
        didSet {
            tableView.registerNib(cellOfType: ReviewTableViewCell.self)
        }
    }
    
    // MARK: - Public properties

    var presenter: ProfilePresenterInterface!

    // MARK: - Private properties

    private lazy var dataSourceDelegate: TableDataSourceDelegate = {
        return TableDataSourceDelegate(tableView: self.tableView)
    }()

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        configure()
        setupUI()
    }
}

// MARK: - Extensions -

extension ProfileViewController: ProfileViewInterface {
}

private extension ProfileViewController {

    func configure() {
        let output = Profile.ViewOutput()

        let input = presenter.configure(with: output)

        handle(items: input.items)
    }

}

private extension ProfileViewController {

    func setupUI() {
        usernameTitleLabel.text = Strings.usernameTitle
        emailTitleLabel.text = Strings.emailTitle
        ratingsCountTitleLabel.text = Strings.ratingsCountTitle
        ratingsSectionLabel.text = Strings.ratingsTitle
    }
}

private extension ProfileViewController {

    func handle(items: Driver<[TableCellItem]>) {
        items
            .drive(dataSourceDelegate.rx.items)
            .disposed(by: disposeBag)
    }
}
