//
//  ProfileInteractor.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa
import CoreData

final class ProfileInteractor {
}

// MARK: - ProfileInteractorInterface

extension ProfileInteractor: ProfileInteractorInterface {

    var profilePhoto: Driver<String?> {
        return UserDefaults.standard.rx
            .observe(String.self, UserStoreManager.profilePhotoKey)
            .asDriver(onErrorDriveWith: .empty())
    }

    func fetchReviews() -> Single<[Review]> {

        return Single.create { observer -> Disposable in

            let request: NSFetchRequest = Review.fetchRequest()

            do {
                let reviews = try PersistanceManager.context.fetch(request)
                observer(.success(reviews))
            } catch (let error) {
                observer(.error(error))
            }

            return Disposables.create { }
        }
    }
}
