//
//  LanguagesInteractor.swift
//  nlp
//
//  Created by Ivana Mršić on 19.11.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class LanguagesInteractor {
}

// MARK: - Extensions -

extension LanguagesInteractor: LanguagesInteractorInterface {
}
