//
//  LanguagesPresenter.swift
//  nlp
//
//  Created by Ivana Mršić on 19.11.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class LanguagesPresenter {

    // MARK: - Private properties -

    private unowned let view: LanguagesViewInterface
    private let interactor: LanguagesInteractorInterface
    private let wireframe: LanguagesWireframeInterface

    // MARK: - Lifecycle -

    init(view: LanguagesViewInterface, interactor: LanguagesInteractorInterface, wireframe: LanguagesWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension LanguagesPresenter: LanguagesPresenterInterface {

    func configure(with output: Languages.ViewOutput) -> Languages.ViewInput {
        return Languages.ViewInput()
    }

}
