//
//  SettingsViewController.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 27.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class SettingsViewController: NLPViewController {

    // MARK: - IBOutlets

    @IBOutlet private weak var tableView: UITableView! {
        didSet {
            self.tableView.registerNib(cellOfType: ImageSelectionTableViewCell.self)
            self.tableView.registerNib(cellOfType: LanguageSelectionTableViewCell.self)
        }
    }

    // MARK: - Public properties

    var presenter: SettingsPresenterInterface!

    // MARK: - Private properties

    private lazy var dataSourceDelegate: TableDataSourceDelegate = {
        return TableDataSourceDelegate(tableView: self.tableView)
    }()

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        configure()
    }
}

// MARK: - SettingsViewInterface

extension SettingsViewController: SettingsViewInterface {
}

// MARK: - Configuration

private extension SettingsViewController {

    func configure() {
        let output = Settings.ViewOutput(
            viewWillAppear: rx.viewWillAppear.asSignal()
        )

        let input = presenter.configure(with: output)
        handle(sections: input.sections)
    }

}

// MARK: - Binding setup

private extension SettingsViewController {

    func handle(sections: Driver<[TableSectionItem]>) {
        sections
            .drive(dataSourceDelegate.rx.sections)
            .disposed(by: disposeBag)
    }
}
