//
//  EditPersonalInfoInterfaces.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 29.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol EditPersonalInfoWireframeInterface: WireframeInterface {
    func dismiss()
}

protocol EditPersonalInfoViewInterface: ViewInterface {
}

protocol EditPersonalInfoPresenterInterface: PresenterInterface {
    func configure(with output: EditPersonalInfo.ViewOutput) -> EditPersonalInfo.ViewInput
}

protocol EditPersonalInfoInteractorInterface: InteractorInterface {
    var username: Driver<String?> { get }
    var email: Driver<String?> { get }
    func updateData(username: String?, email: String?)
}

enum EditPersonalInfo {

    struct ViewOutput {
        let saveAction: Signal<Void>
        let username: Driver<String?>
        let email: Driver<String?>
    }

    struct ViewInput {
        let username: Driver<String?>
        let email: Driver<String?>
    }

}
