//
//  EditPersonalInfoWireframe.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 29.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class EditPersonalInfoWireframe: BaseWireframe {

    // MARK: - Private properties

    private let storyboard = UIStoryboard.editPersonalInfo

    // MARK: - Module setup

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: EditPersonalInfoViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = EditPersonalInfoInteractor()
        let presenter = EditPersonalInfoPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - EditPersonalInfoWireframeInterface

extension EditPersonalInfoWireframe: EditPersonalInfoWireframeInterface {

    func close() {
        navigationController?.popViewController(animated: true)
    }
}
