//
//  ChoosePhotoViewController.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ChoosePhotoViewController: NLPViewController {

    // MARK: - IBOutlets

    @IBOutlet private weak var titleLabel: UILabel!
    @IBOutlet private weak var tableView: UITableView! {
        didSet {
            tableView.registerNib(cellOfType: PhotoTableViewCell.self)
        }
    }
    
    // MARK: - Public properties

    var presenter: ChoosePhotoPresenterInterface!

    // MARK: - Private properties

    private lazy var dataSourceDelegate: TableDataSourceDelegate = {
        return TableDataSourceDelegate(tableView: self.tableView)
    }()

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        configure()
        setupUI()
    }
	
}

// MARK: - ChoosePhotoViewInterface

extension ChoosePhotoViewController: ChoosePhotoViewInterface {
}

// MARK: - Configuration

private extension ChoosePhotoViewController {

    func configure() {
        let output = ChoosePhoto.ViewOutput()

        let input = presenter.configure(with: output)
        handle(items: input.items)
    }
}

// MARK: - UI Setup

private extension ChoosePhotoViewController {

    func setupUI() {
        titleLabel.text = Strings.choosePhotoTitle
    }
}

// MARK: - Binding Setup

private extension ChoosePhotoViewController {

    func handle(items: Driver<[TableCellItem]>) {
        items.drive(dataSourceDelegate.rx.items)
            .disposed(by: disposeBag)
    }
}
