//
//  ChoosePhotoInteractor.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class ChoosePhotoInteractor {

}

// MARK: - ChoosePhotoInteractorInterface

extension ChoosePhotoInteractor: ChoosePhotoInteractorInterface {

    func save(photo: ProfilePhoto) {
        UserStoreManager.profilePhoto = photo.imageName
    }
}
