//
//  ChoosePhotoInterfaces.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol ChoosePhotoWireframeInterface: WireframeInterface {
    func dismiss()
}

protocol ChoosePhotoViewInterface: ViewInterface {
}

protocol ChoosePhotoPresenterInterface: PresenterInterface {
    func configure(with output: ChoosePhoto.ViewOutput) -> ChoosePhoto.ViewInput
}

protocol ChoosePhotoInteractorInterface: InteractorInterface {
    func save(photo: ProfilePhoto)
}

enum ChoosePhoto {

    struct ViewOutput {
    }

    struct ViewInput {
        let items: Driver<[TableCellItem]>
    }

}
