//
//  ChoosePhotoWireframe.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 26.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ChoosePhotoWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard.choosePhoto

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: ChoosePhotoViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = ChoosePhotoInteractor()
        let presenter = ChoosePhotoPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - ChoosePhotoWireframeInterface

extension ChoosePhotoWireframe: ChoosePhotoWireframeInterface {

    func dismiss() {
        viewController.dismiss(animated: true, completion: nil)
    }
}
