//
//  FilterReviewsWireframe.swift
//  SentimentClassifier
//
//  Created by Ivana Mršić on 27.12.2020..
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class FilterReviewsWireframe: BaseWireframe {

    // MARK: - Private properties

    private let storyboard = UIStoryboard.filterReviews

    // MARK: - Module setup

    init(delegate: FilterDelegate) {
        let moduleViewController = storyboard.instantiateViewController(ofType: FilterReviewsViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = FilterReviewsInteractor()
        let presenter = FilterReviewsPresenter(view: moduleViewController, interactor: interactor, wireframe: self, delegate: delegate)
        moduleViewController.presenter = presenter
    }

}

// MARK: - FilterReviewsWireframeInterface

extension FilterReviewsWireframe: FilterReviewsWireframeInterface {

    func dismiss() {
        viewController.dismiss(animated: true, completion: nil)
    }
}
